name: PlatformIO

on:
  push:
    branches:
      - devel

  pull_request:
    branches:
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          pio pkg update
      - name: Testing build for Release-twatch2020_V3
        run: |
          touch openWeatherKey.txt
          touch omdbKey.txt
          pio run -e Release-twatch2020_V3
      - name: Testing build for Debug-twatch2020_V3
        run: |
          touch openWeatherKey.txt
          touch omdbKey.txt
          pio run -e Debug-twatch2020_V3
 
